version: '3.7'

services:  
  api:
    image: docker.io/library/user-management-service-api:latest
    env_file:
      - .env
    ports:
      - "${PORT}:8080"
    networks:
      - user-management

networks:
  user-management: